### ISSUE TITLE
How to use? install?

### ISSUE THREAD

**Issue by obcocav** [featherbear/NDI-Telestrator#13]
So this is obviously a noob question.....How do I install and use this?  I don't see any instructions in the readme.  I'm sure I'm missing something completely obvious, but I appreciate any help here!  :)

**Comment by featherbear** [comment]
Hey there @obcocav, you can find the download here - https://github.com/featherbear/NDI-Telestrator/releases

Please note that this project was a test exploration though, and I don't really have any future intentions of updating it or making changes (unless there becomes a personal need to)

**Comment by dtseiler** [comment]
Does this run on the PC then? I was looking for something that would run on my Android tablet, taking the NDI feed of a video, letting me draw over it and then sending that back to OBS via NDI. Something like we see [in this video](https://www.youtube.com/watch?v=QPs7E5m-pO4)

**Comment by featherbear** [comment]
Yeah this runs on the PC.

From that video (is that an iPad?) it seems like he is using some remote software to control a PC.
In theory this could be a native Android application, as NDI 5 supports both decode and encode of streams
